DECLARE
    v_user_id BANK_USERS.USER_ID%TYPE;
BEGIN
    SELECT USER_ID INTO v_user_id FROM BANK_USERS WHERE SUBJECT = 'alice';
    BEGIN
        INSERT INTO ACCOUNTS (ACCOUNT_ID, OWNER_ID, ACCOUNT_TYPE, CURRENCY, BALANCE)
        VALUES ('acc_alice_checking', v_user_id, 'CHECKING', 'USD', 3200.00);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;
    BEGIN
        INSERT INTO ACCOUNTS (ACCOUNT_ID, OWNER_ID, ACCOUNT_TYPE, CURRENCY, BALANCE)
        VALUES ('acc_alice_savings', v_user_id, 'SAVINGS', 'USD', 8750.00);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;
    COMMIT;
END;
/
SELECT A.ACCOUNT_ID, A.ACCOUNT_TYPE, A.BALANCE
FROM ACCOUNTS A
JOIN BANK_USERS U ON A.OWNER_ID = U.USER_ID
WHERE U.SUBJECT = 'alice';
EXIT
